In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle_age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle_age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle_age,365

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   object
 16  frequency_of_purchases  3900 non-null   object
 17  age_group               3900 non-null   object
 18  purchase_frequency_day  3900 non-null   int64
dtypes: float64(1), int64(5), object(13)
memory usage: 579.0+ KB

In [5]:
df.describe(include='all')

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_day
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900.000000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,NaN,6,7,4,NaN
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,NaN,PayPal,Every 3 Months,Young_adult,NaN
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,NaN,677,584,1028,NaN
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750051,NaN,NaN,NaN,25.351538,NaN,NaN,NaN,89.133077
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.713590,NaN,NaN,NaN,14.447125,NaN,NaN,NaN,119.037566
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,7.000000
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,13.000000,NaN,NaN,NaN,14.000000
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,30.000000
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,90.000000
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,365.000000

In [6]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
age_group                 0
purchase_frequency_day    0
dtype: int64

In [7]:
df['Review Rating']= df.groupby('category')['review_rating'].transform(lambda x:x.fillna(x.median()))

In [8]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
age_group                 0
purchase_frequency_day    0
Review Rating             0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   object
 16  frequency_of_purchases  3900 non-null   object
 17  age_group               3900 non-null   object
 18  purchase_frequency_day  3900 non-null   int64
 19  review_rating           3900 non-null   float64
dtypes: float64(2), int64(5), object(13)
memory usage: 609.5+ KB

In [11]:
labels= ['Young_adult','Adult','Middle_age','Senior']
df['age_group']= pd.qcut(df['age'],q=4, labels=labels)

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   55   Middle_age
1   19  Young_adult
2   50   Middle_age
3   21  Young_adult
4   45   Middle_age
5   46   Middle_age
6   63       Senior
7   27  Young_adult
8   26  Young_adult
9   57   Middle_age

In [13]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_day']=df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['purchase_frequency_day','frequency_of_purchases']].head(10)

   purchase_frequency_day frequency_of_purchases
0                      14            Fortnightly
1                      14            Fortnightly
2                       7                 Weekly
3                       7                 Weekly
4                     365               Annually
5                       7                 Weekly
6                      90              Quarterly
7                       7                 Weekly
8                     365               Annually
9                      90              Quarterly

In [17]:
df['discount_applied'].head(10)

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
5    Yes
6    Yes
7    Yes
8    Yes
9    Yes
Name: discount_applied, dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   object
 16  frequency_of_purchases  3900 non-null   object
 17  age_group               3900 non-null   category
 18  purchase_frequency_day  3900 non-null   int64
 19  review_rating           3900 non-null   float64
dtypes: category(1), float64(2), int64(5), object(12)
memory usage: 583.0+ KB

In [20]:
df.to_csv("customer_shopping_behavior.csv", index=False)